/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var c=Object.defineProperty;var g=Object.getOwnPropertyDescriptor;var C=Object.getOwnPropertyNames;var I=Object.prototype.hasOwnProperty;var P=(e,t)=>{for(var a in t)c(e,a,{get:t[a],enumerable:!0})},y=(e,t,a,r)=>{if(t&&typeof t=="object"||typeof t=="function")for(let n of C(t))!I.call(e,n)&&n!==a&&c(e,n,{get:()=>t[n],enumerable:!(r=g(t,n))||r.enumerable});return e};var A=e=>y(c({},"__esModule",{value:!0}),e);var E={};P(E,{default:()=>l});module.exports=A(E);var f=require("obsidian");var m=`## Basic Info
#### Name

#### Meaning of Name

#### Nicknames

#### Date of Birth

## Appearance
#### Hair Color

#### Hair Type / Length

#### Eye Color

#### Skin Tone

#### Race

#### Extra

## Relations
#### Family

#### Friends

#### Allies

#### Enemies

#### Other

`;var S=`# Main Details
## Basic Info
#### Name

#### Class

#### Level

#### Background

#### Player Name

#### Race

#### Alignment

#### XP

## Ability Scores
### Strength
#### Score

#### Modifier
**+**
### Dexterity
#### Score

#### Modifier
**+**
### Constitution
#### Score

#### Modifier
**+**
### Intelligence
#### Score

#### Modifier
**+**
### Wisdom
#### Score

#### Modifier
**+**
### Charisma
#### Score

#### Modifier
**+**

#### Inspiration

#### Proficiency Bonus
**+**
## Saving Throws
#### Strength
- [ ] 
**+**
#### Dexterity
- [ ] 
**+**
#### Constitution
- [ ] 
**+**
#### Intelligence
- [ ] 
**+**
#### Wisdom
- [ ] 
**+**
#### Charisma
- [ ] 
**+**

## Skills
#### Acrobatics
Inherits from: *Dexterity*
- [ ] 
**+**
#### Animal Handling
Inherits from: *Wisdom*
- [ ] 
**+**
#### Arcana
Inherits from: *Intelligence*
- [ ] 
**+**
#### Athletics
Inherits from: *Strength*
- [ ] 
**+**
#### Deception
Inherits from: *Charisma*
- [ ] 
**+**
#### History
Inherits from: *Intelligence*
- [ ] 
**+**
#### Insight
Inherits from: *Wisdom*
- [ ] 
**+**
#### Intimidation
Inherits from: *Charisma*
- [ ] 
**+**
#### Investigation
Inherits from: *Intelligence*
- [ ] 
**+**
#### Medicine
Inherits from: *Wisdom*
- [ ] 
**+**
#### Nature
Inherits from: *Intelligence*
- [ ] 
**+**
#### Perception
Inherits from: *Wisdom*
- [ ] 
**+**
#### Performance
Inherits from: *Charisma*
- [ ] 
**+**
#### Persuasion
Inherits from: *Charisma*
- [ ] 
**+**
#### Religion
Inherits from: *Intelligence*
- [ ] 
**+**
#### Sleight of Hand
Inherits from: *Dexterity*
- [ ] 
**+**
#### Stealth
Inherits from: *Dexterity*
- [ ] 
**+**
#### Survival
Inherits from: *Wisdom*
- [ ] 
**+**
#### Passive Wisdom (Perception)

#### Other Proficiencies & Languages
- 

## Combat Stats
#### Armor Class

#### Intiative

#### Speed

#### Hit Point Max

#### Current Hit Points

#### Temporary Hit Points

#### Hit Dice

### Death Saves
#### Successes
- [ ] \u263A\uFE0F
- [ ] \u263A\uFE0F
- [ ] \u263A\uFE0F
#### Failures
- [ ] \u{1F480}
- [ ] \u{1F480}
- [ ] \u{1F480}

## Attacks and Spellcasting
### Weapon 1
#### Name

#### Attack Bonus
**+**
#### Damage Type

### Weapon 2
#### Name

#### Attack Bonus
**+**
#### Damage Type

### Weapon 3
#### Name

#### Attack Bonus
**+**
#### Damage Type

### Weapon Notes
- 

## Inventory
#### Copper Pieces (CP)

#### Silver Pieces (SP)

#### Electrum Pieces (EP)

#### Gold Pieces (GP)

#### Platinum Pieces (PP)

#### Equipment
- 

## Characteristics
#### Personality Traits

#### Ideals

#### Bonds

#### Flaws

#### Features & Traits
- 

# Personal Details
## Basic Info
#### Name

#### Age

#### Height

#### Weight

#### Eyes

#### Skin

#### Hair

#### Character Appearance


## Allies & Organizations
#### Allies

#### Organizations


## Character Backstory
- 

## Additional Features and Traits
- 

## Treasure
- 

# Spellcasting Details
## Basic Info
#### Spellcasting Class

#### Spellcasting Ability

#### Spell Save DC

#### Spellcasting Bonus


## Cantrips & Spells
#### Cantrips

### 1st Level
#### Slots Expended

#### Spells
- 
### 2nd Level
#### Slots Expended

#### Spells
- 
### 3rd Level
#### Slots Expended

#### Spells
- 
### 4th Level
#### Slots Expended

#### Spells
- 
### 5th Level
#### Slots Expended

#### Spells
- 
### 6th Level
#### Slots Expended

#### Spells
- 
### 7th Level
#### Slots Expended

#### Spells
- 
### 8th Level
#### Slots Expended

#### Spells
- 
### 9th Level
#### Slots Expended

#### Spells
- 

`;function v(e){switch(e){case 0:return m;case 1:return S;default:return m}}function x(e){e.getFolderByPath("Characters")===null&&e.createFolder("Characters")}async function i(e,t){let a=e.vault,r=Math.floor(Math.random()*9e4);x(e.vault),await a.create(`Characters/Character${r}.md`,v(t));let n=e.vault.getFileByPath(`Characters/Character${r}.md`);e.workspace.getLeaf("tab").openFile(n)}function d(e){return{id:"new-standard-cs",name:"New standard character sheet",callback:()=>{i(e,0)}}}function h(e){return{id:"new-dnd-cs",name:"New D&D character sheet",callback:()=>{i(e,1)}}}function p(e){let t=[d(e.app),h(e.app)];for(let a of t)e.addCommand(a)}var s=require("obsidian"),o=class extends s.Modal{constructor(t,a){super(t),this.setTitle("Character sheets"),this.setContent("Select a character sheet to generate!");let r="0";new s.Setting(this.contentEl).addDropdown(n=>{n.addOption("0","Standard character").addOption("1","D&D character").onChange(u=>{r=u})}),new s.Setting(this.contentEl).addButton(n=>{n.setButtonText("Create sheet").setCta().onClick(()=>{this.close(),a(r)})})}};var D={mySetting:"default"},l=class extends f.Plugin{async onload(){this.addRibbonIcon("user-pen","Create new character sheet ",()=>{new o(this.app,a=>i(this.app,+a)).open()}),p(this)}async loadSettings(){this.settings=Object.assign({},D,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}};

/* nosourcemap */